name: Build and Push app into AWS ECR

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build-and-push-all:
    name: Build & Deploy ALL into aws ECR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add new apps when are created
        appName:
          - app1
          - app2
          - app3
          - app4
          - nest-js-github-actions-monorepo
    uses: ./.github/workflows/build-and-push-app.yml
    with:
      appName: ${{ matrix.appName }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
