name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      appName:
        description: App to deploy
        required: true
        type: choice
        # Add new apps when are created
        options:
          - app1
          - app2
          - app3
          - app4
          - nest-js-github-actions-monorepo
          - ALL
      namespace:
        description: Dest environment
        required: true
        default: alpha
        type: choice
        options:
          - alpha
          - beta
          - production
jobs:
  build-and-push-app:
    uses: ./.github/workflows/build-and-push-app.yml
    if: ${{ inputs.appName != 'ALL' }}
    with:
      appName: ${{ inputs.appName }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  build-and-push-all:
    uses: ./.github/workflows/build-and-push-all.yml
    if: ${{ inputs.appName == 'ALL' }
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}


