name: Manual deploy launch

on:
  workflow_dispatch:
    inputs:
      appName:
        description: App to deploy
        required: true
        type: choice
        options:
          - app1
          - app2
          - app3
          - app4
          - ALL
      namespace:
        description: Dest environment
        required: true
        default: alpha
        type: choice
        options:
          - alpha
          - beta
          - production
jobs:
  build-and-push:
    name: Build specified docker images and deploy into aws ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print variables
        run: |
          echo "appName selected: $github.event.inputs.appName"
          echo "namespace selected: $github.event.inputs.namespace"

      - name: Build & Push into ECR app $github.event.inputs.appName
        if: ${{ github.event.inputs.appName != 'ALL' }}
        run: |
          echo "Deploy app: ${{ github.event.inputs.appName }} into namespace: ${{ github.event.inputs.namespace }}"

      - name: 'Deploy ALL APPS'
        if: ${{ github.event.inputs.appName == 'ALL' }}
        run: |
          echo "Deploy ALL apps into namespace: ${{ github.event.inputs.namespace }}"

