name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      appName:
        description: App to deploy
        required: true
        type: choice
        options:
          - app1
          - app2
          - app3
          - app4
          - nest-js-github-actions-monorepo
          - ALL
      namespace:
        description: Dest environment
        required: true
        default: alpha
        type: choice
        options:
          - alpha
          - beta
          - production
jobs:
  build-and-push-app:
    name: Build & Deploy App into aws ECR
    if: ${{ inputs.appName != 'ALL' }}
    runs-on: ubuntu-latest
    steps:
      - name: Specific App => Build & Push into ECR
        uses: CristianBB/nestJsGithubActionsMonorepo/.github/workflows/build-and-push.yml@main
        with:
          appName: ${{ inputs.appName }}

  build-and-push-all:
    name: Build & Deploy ALL Apps into aws ECR
    if: ${{ inputs.appName == 'ALL' }}
    steps:
      run: |
        echo "Deploy ALL apps into namespace: ${{ inputs.namespace }}"

