name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      appName:
        description: App to deploy
        required: true
        type: choice
        # Add new apps when are created
        options:
          - app1
          - app2
          - app3
          - app4
          - nest-js-github-actions-monorepo
          - ALL
      namespace:
        description: Dest environment
        required: true
        default: alpha
        type: choice
        options:
          - alpha
          - beta
          - production
jobs:
  build-one:
    uses: ./.github/workflows/build-and-push.yml
    if: ${{ inputs.appName != 'ALL' }}
    with:
      appName: ${{ inputs.appName }}
      awsRegion: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-one:
    uses: ./.github/workflows/deploy-argocd.yml
    needs: build-one
    with:
      appName: ${{ inputs.appName }}
      ecrRegistry: ${{ needs.build-one.outputs.ecrRegistry }}
      imageTag: ${{ needs.build-one.outputs.imageTag }}
      namespace: ${{ inputs.namespace }}
    secrets:
      ARGOCD_REPO: ${{ secrets.ARGOCD_REPO }}
      PAT_DEPLOY: ${{ secrets.PAT_DEPLOY }}

  build-all:
    uses: ./.github/workflows/build-and-push.yml
    if: ${{ inputs.appName == 'ALL' }}
    strategy:
      matrix:
        # Add new apps when are created
        appName:
          - app1
          - app2
          - app3
          - app4
          - nest-js-github-actions-monorepo
    with:
      appName: ${{ matrix.appName }}
      awsRegion: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-all:
    uses: ./.github/workflows/deploy-argocd.yml
    needs: build-all
    strategy:
      matrix:
        # Add new apps when are created
        appName:
          - app1
          - app2
          - app3
          - app4
          - nest-js-github-actions-monorepo
    with:
      appName: ${{ matrix.appName }}
      ecrRegistry: ${{ needs.build-all.outputs.ecrRegistry }}
      imageTag: ${{ needs.build-all.outputs.imageTag }}
      namespace: ${{ inputs.namespace }}
    secrets:
      ARGOCD_REPO: ${{ secrets.ARGOCD_REPO }}
      PAT_DEPLOY: ${{ secrets.PAT_DEPLOY }}

