name: Test changed files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3
        with:
          files: |
            apps/*
          dir_names: true

      - name: List all changed files
        run: |
          for path in ${{ steps.changed-files.outputs.all_changed_files }}; do
            app=$(echo "$path" | sed -e 's/apps\///g' | sed -e 's/\/.*//g')
            echo "$path was changed => $app"
          done
